// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

// InitializeApp выполняет инициализацию всего приложения
func InitializeApp() (*App, error) {
	config := ProvideConfig()
	logger := ProvideLogger()
	subPub := ProvideSubPub(logger)
	server := ProvideServer(config, logger, subPub)
	app := NewApp(config, logger, server)
	return app, nil
}
